module Videos
    
   def self.video_array
    
    ["https://www.youtube.com/watch?v=XnBBCb0GjVg", 
    "https://www.youtube.com/watch?v=xvo302Bu4KA", 
    "https://www.youtube.com/watch?v=0VVtImcGTes", 
    "https://www.youtube.com/watch?v=7goI2ROVwiw", 
    "https://www.youtube.com/watch?v=_qODa1tYF2w", 
    "https://www.youtube.com/watch?v=iimB7ReWFjw", 
    "https://www.youtube.com/watch?v=hehwvwo7y8c", 
    "https://www.youtube.com/watch?v=DabyCR0rfeE", 
    "https://www.youtube.com/watch?v=iSgPJGzA5mQ", 
    "https://www.youtube.com/watch?v=dizUs72YNz0", 
    "https://www.youtube.com/watch?v=Qta9HpZD0-M", 
    "https://www.youtube.com/watch?v=GFLH0noBBpw", 
    "https://www.youtube.com/watch?v=Sy5rmAhen98", 
    "https://www.youtube.com/watch?v=Vs_DkAzMoVM", 
    "https://www.youtube.com/watch?v=88Sxz6qRyCk", 
    "https://www.youtube.com/watch?v=tc6rhyPndVE",  
    "https://www.youtube.com/watch?v=7CnyVcrCh38",
    "https://www.youtube.com/watch?v=s4qbCVSTIms",
    "https://www.youtube.com/watch?v=Yk0srAU18NU",
    "https://www.youtube.com/watch?v=9EvL5nODVHg",
    "https://www.youtube.com/watch?v=JH0APkbuGaU",
    "https://www.youtube.com/watch?v=VWGPxsyZfFs",
    "https://www.youtube.com/watch?v=aJDJl9drHO8",
    "https://www.youtube.com/watch?v=lbClYCIFHk4",
    "https://www.youtube.com/watch?v=rUzbyBGCBgw",
    "https://www.youtube.com/watch?v=UCAEQUuUhqk",
    "https://www.youtube.com/watch?v=6aRTAFAwkwU",
    "https://www.youtube.com/watch?v=9JTtu_T9sKo",
    "https://www.youtube.com/watch?v=XkOYTtY5JSU",
    "https://www.youtube.com/watch?v=XkOYTtY5JSU",
    "https://www.youtube.com/watch?v=tDYwE8zLt9M",
    "https://www.youtube.com/watch?v=9m4xUu3NrLA",
    "https://www.youtube.com/watch?v=WiKQVGhm4U0",
    "https://www.youtube.com/watch?v=WiKQVGhm4U0",
    "https://www.youtube.com/watch?v=rMjqHFApfX0",
    "https://www.youtube.com/watch?v=Vg3YM6Uv_dg",
    "https://www.youtube.com/watch?v=88EUKTByPZQ",
] 
   end  

end 